import React from "react";
import Head from "next/head";
import LottieAnimation from "../components/LottieAnimation";
import Gift from "../animation/gift.json";
import { LockClosedIcon } from "@heroicons/react/outline";
import Refer from "../components/refer";
import Rewards from "../components/rewards";

function gift() {
  return (
    <div className="flex flex-col gap-5 bg-blue-50 h-screen">
      <Head>
        <title>Gift</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-blue-700 pt-5 h-20 px-4 ">
        <p className="text-xs text-gray-300 ">Total Rewards Earned</p>
        <p className="text-white text-xl">₹205</p>
      </div>
      {/* refer */}
      <Refer />
      <p className="text-sm text-gray-500 font-bold pt-5 px-4">Rewards</p>
      {/* rewards */}
      <Rewards />
    </div>
  );
}

export default gift;
