import React from "react";
import Head from "next/head";
import LottieAnimation from "../components/LottieAnimation";
import Gift from "../animation/gift.json";
import { LockClosedIcon } from "@heroicons/react/outline";

function gift() {
  return (
    <div className="flex flex-col gap-5 bg-blue-50 h-screen">
      <Head>
        <title>Gift</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-blue-700 pt-5 h-20 px-4 ">
        <p className="text-xs text-gray-300 ">Total Rewards Earned</p>
        <p className="text-white text-xl">₹205</p>
      </div>
      {/* refer */}
      <div className=" px-4">
        <p className="text-sm text-gray-500 font-bold py-3">Refer Now</p>
        <div>
          <a className="flex items-center justify-start px-4 gap-4 bg-gray-100 py-2 ">
            <div>
              <p className="text-sm text-gray-500 font-bold">
                Refer and Earn FREE BITCOINS
              </p>
              <p className="text-xs text-gray-500">
                Earn ₹50 worth of free BTC by inviting your friends to join
              </p>
            </div>
            <div>
              <LottieAnimation lotti={Gift} height={80} width={80} />
            </div>
          </a>
        </div>
      </div>
      <p className="text-sm text-gray-500 font-bold pt-5 px-4">Rewards</p>
      {/* rewards */}
      <div className="px-4 flex gap-2 justify-center">
        <div className="w-40 h-40 border-2 border-gray-200 bg-blue-400 flex items-center justify-center relative">
          <LockClosedIcon className="h-10 text-white" />
          <div className="flex flex-col items-center justify-center mt-5 absolute w-full bg-blue-700 h-8 bottom-0">
            <p className="text-white px-3 text-xs ">Rewards coming soon</p>
          </div>
        </div>
        <div className="w-40 h-40 border-2 border-gray-200 bg-blue-400 flex items-center justify-center relative">
          <LockClosedIcon className="h-10 text-white" />
          <div className="flex flex-col items-center justify-center mt-5 absolute w-full bg-blue-700 h-8 bottom-0">
            <p className="text-white px-3 text-xs ">Rewards coming soon</p>
          </div>
        </div>
      </div>
    </div>
  );
}

export default gift;
