import Head from "next/head";
import {
  QuestionMarkCircleIcon,
  CurrencyDollarIcon,
} from "@heroicons/react/outline";
import LottieAnimation from "../components/LottieAnimation";
import Gift from "../animation/gift.json";
import Buttons from "../components/buttons";
import InvestedCurrency from "../components/investedCurrency";
import { netWorth } from "../constants/indexConstants";
import Choices from "../components/choices";
import Refer from "../components/refer";

export default function Home() {
  return (
    <div className="px-3 flex flex-col gap-3 bg-blue-50">
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* total worth */}
      <div className="flex flex-col mt-5 p-1 bg-gray-100">
        <div>
          <p className="text-xs">Total Worth</p>
        </div>
        <div className="flex items-center gap-1 py-1">
          <p className="text-2xl font-semibold">{netWorth}</p>
          <QuestionMarkCircleIcon className="w-5" />
        </div>
      </div>
      {/* buttons */}
      <Buttons />
      {/* banner */}
      {/* watchlist */}
      <div className="flex justify-between py-1 px-2 bg-gray-100">
        <p className="text-sm">Watchlist</p>
        <p className="text-sm text-blue-800">Add More</p>
      </div>
      {/* invested currencies */}
      <InvestedCurrency />
      {/* popular currencies */}
      <div className="bg-gray-100">
        <div className="flex justify-between py-2 px-2">
          <p className="text-base">Popular Currencies</p>
          <p className="text-sm text-blue-800">Add More</p>
        </div>
      </div>
      {/* choices */}
      <Choices />
      {/* refer */}
      <Refer/>
    </div>
  );
}
