import React from "react";
import Head from "next/head";
import { CurrencyDollarIcon, SearchIcon } from "@heroicons/react/outline";
function market() {
  return (
    <div className="px-3 flex flex-col gap-5 bg-blue-50">
      <Head>
        <title>Market</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex justify-between px-1 items-center mt-5 py-3">
        <p>
          Market is <span className="text-green-400"> up 0.65% </span>
          <span className="text-xs">in last 24h</span>
        </p>
        <SearchIcon className="font-bold h-6 text-blue-400" />
      </div>
      <div className="flex shadow-lg bg-white items-center">
        <div className="px-8 text-blue-400 border-b-4 border-blue-400 py-2">
          <p>All</p>
        </div>
        <div className="px-8">
          <p>Watchlist</p>
        </div>
        <div className="px-8 whitespace-nowrap">
          <p>Top Gainers</p>
        </div>
      </div>
      {/* invested currencies */}
      <div className="flex justify-between py-1 px-3 bg-gray-100">
        <div className="flex items-center gap-2">
          <CurrencyDollarIcon className="w-7 bg-yellow-600 rounded-full text-white" />
          <div>
            <p>Bitcoin</p>
            <p>BTC</p>
          </div>
        </div>
        <div>
          <p>₹44,55,647.48</p>
          <p className="text-green-400 text-right">10%</p>
        </div>
      </div>
      <div className="flex justify-between py-1 px-3 bg-gray-100">
        <div className="flex items-center gap-2">
          <CurrencyDollarIcon className="w-7 bg-yellow-600 rounded-full text-white" />
          <div>
            <p>Bitcoin</p>
            <p>BTC</p>
          </div>
        </div>
        <div>
          <p>₹44,55,647.48</p>
          <p className="text-green-400 text-right">10%</p>
        </div>
      </div>
      <div className="flex justify-between py-1 px-3 bg-gray-100">
        <div className="flex items-center gap-2">
          <CurrencyDollarIcon className="w-7 bg-yellow-600 rounded-full text-white" />
          <div>
            <p>Bitcoin</p>
            <p>BTC</p>
          </div>
        </div>
        <div>
          <p>₹44,55,647.48</p>
          <p className="text-green-400 text-right">10%</p>
        </div>
      </div>
      <div className="flex justify-between py-1 px-3 bg-gray-100">
        <div className="flex items-center gap-2">
          <CurrencyDollarIcon className="w-7 bg-yellow-600 rounded-full text-white" />
          <div>
            <p>Bitcoin</p>
            <p>BTC</p>
          </div>
        </div>
        <div>
          <p>₹44,55,647.48</p>
          <p className="text-green-400 text-right">10%</p>
        </div>
      </div>
      <div className="flex justify-between py-1 px-3 bg-gray-100">
        <div className="flex items-center gap-2">
          <CurrencyDollarIcon className="w-7 bg-yellow-600 rounded-full text-white" />
          <div>
            <p>Bitcoin</p>
            <p>BTC</p>
          </div>
        </div>
        <div>
          <p>₹44,55,647.48</p>
          <p className="text-green-400 text-right">10%</p>
        </div>
      </div>
      <div className="flex justify-between py-1 px-3 bg-gray-100">
        <div className="flex items-center gap-2">
          <CurrencyDollarIcon className="w-7 bg-yellow-600 rounded-full text-white" />
          <div>
            <p>Bitcoin</p>
            <p>BTC</p>
          </div>
        </div>
        <div>
          <p>₹44,55,647.48</p>
          <p className="text-green-400 text-right">10%</p>
        </div>
      </div>
      <div className="flex justify-between py-1 px-3 bg-gray-100">
        <div className="flex items-center gap-2">
          <CurrencyDollarIcon className="w-7 bg-yellow-600 rounded-full text-white" />
          <div>
            <p>Bitcoin</p>
            <p>BTC</p>
          </div>
        </div>
        <div>
          <p>₹44,55,647.48</p>
          <p className="text-green-400 text-right">10%</p>
        </div>
      </div>
      <div className="flex justify-between py-1 px-3 bg-gray-100">
        <div className="flex items-center gap-2">
          <CurrencyDollarIcon className="w-7 bg-yellow-600 rounded-full text-white" />
          <div>
            <p>Bitcoin</p>
            <p>BTC</p>
          </div>
        </div>
        <div>
          <p>₹44,55,647.48</p>
          <p className="text-green-400 text-right">10%</p>
        </div>
      </div>
      <div className="flex justify-between py-1 px-3 bg-gray-100">
        <div className="flex items-center gap-2">
          <CurrencyDollarIcon className="w-7 bg-yellow-600 rounded-full text-white" />
          <div>
            <p>Bitcoin</p>
            <p>BTC</p>
          </div>
        </div>
        <div>
          <p>₹44,55,647.48</p>
          <p className="text-green-400 text-right">10%</p>
        </div>
      </div>
      <div className="flex justify-between py-1 px-3 bg-gray-100">
        <div className="flex items-center gap-2">
          <CurrencyDollarIcon className="w-7 bg-yellow-600 rounded-full text-white" />
          <div>
            <p>Bitcoin</p>
            <p>BTC</p>
          </div>
        </div>
        <div>
          <p>₹44,55,647.48</p>
          <p className="text-green-400 text-right">10%</p>
        </div>
      </div>
      <div className="flex justify-between py-1 px-3 bg-gray-100">
        <div className="flex items-center gap-2">
          <CurrencyDollarIcon className="w-7 bg-yellow-600 rounded-full text-white" />
          <div>
            <p>Bitcoin</p>
            <p>BTC</p>
          </div>
        </div>
        <div>
          <p>₹44,55,647.48</p>
          <p className="text-green-400 text-right">10%</p>
        </div>
      </div>
    </div>
  );
}

export default market;
