import React from "react";
import Head from "next/head";
import styles from "../styles/Home.module.css";
function portfolio() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p>Portfolio</p>
    </div>
  );
}

export default portfolio;
