import React from "react";
import Head from "next/head";
import {
  SwitchHorizontalIcon,
  ChevronRightIcon,
  CurrencyDollarIcon,
} from "@heroicons/react/outline";
import LottieAnimation from "../components/LottieAnimation";
import wallet from "../animation/wallet.json";
import Gift from "../animation/gift.json";

function portfolio() {
  return (
    <div className="px-3 flex flex-col gap-5 bg-blue-50">
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* portfolio */}
      <div className="flex mt-5 px-2 py-3 bg-gray-100 items-center justify-between">
        <div>
          <p className="text-lg">Portfolio</p>
        </div>
        <div className="flex items-center gap-1 py-1 text-blue-500">
          <SwitchHorizontalIcon className="w-4" />
          <p className="text-sm font-semibold">Orders</p>
        </div>
      </div>
      {/* value */}
      <div className="flex justify-between px-2 py-2">
        <div className="flex flex-col gap-1">
          <p className="text-xs">Current Value</p>
          <p>₹205</p>
        </div>
        <div className="flex flex-col gap-1">
          <p className="text-xs">Current Value</p>
          <p>₹205</p>
        </div>
        <div className="flex flex-col gap-1">
          <p className="text-xs">Current Value</p>
          <p className="text-green-400">%20</p>
        </div>
      </div>
      {/* wallet */}
      <div>
        <div className="bg-blue-200 flex items-center justify-between px-1 py-5 rounded-lg">
          <div className="flex items-center gap-5">
            <div className="bg-blue-400 rounded-full ml-3">
              <LottieAnimation lotti={wallet} height={40} width={40} />
            </div>
            <div>
              <p className="text-xs">Total INR Balance</p>
              <p>₹205</p>
            </div>
          </div>
          <div>
            <ChevronRightIcon className="h-5" />
          </div>
        </div>
        <p className="text-center py-1 text-blue-500">DEPOSITE INR</p>
      </div>
      {/* invested currencies */}
      <div className="flex justify-between py-1 px-3 bg-gray-100">
        <div className="flex items-center gap-2">
          <CurrencyDollarIcon className="w-7 bg-yellow-600 rounded-full text-white" />
          <div>
            <p>Bitcoin</p>
            <p>BTC</p>
          </div>
        </div>
        <div>
          <p>₹44,55,647.48</p>
          <p className="text-green-400 text-right">10%</p>
        </div>
      </div>
      <div className="flex justify-between py-1 px-3 bg-gray-100">
        <div className="flex items-center gap-2">
          <CurrencyDollarIcon className="w-7 bg-yellow-600 rounded-full text-white" />
          <div>
            <p>Bitcoin</p>
            <p>BTC</p>
          </div>
        </div>
        <div>
          <p>₹44,55,647.48</p>
          <p className="text-green-400 text-right">10%</p>
        </div>
      </div>
      {/* refer */}
      <div>
        <div>
          <a className="flex items-center justify-start px-4 gap-4 bg-gray-100 py-2 ">
            <div>
              <p className="text-sm text-gray-500 font-bold">
                Refer and Earn FREE BITCOINS
              </p>
              <p className="text-xs text-gray-500">
                Earn ₹50 worth of free BTC by inviting your friends to join
              </p>
            </div>
            <div>
              <LottieAnimation lotti={Gift} height={80} width={80} />
            </div>
          </a>
        </div>
      </div>
    </div>
  );
}

export default portfolio;
